export const techStackData = [
  { name: "Python", icon: "python", local: false },
  { name: "PostgreSQL", icon: "postgresql", local: false },
  { name: "R", icon: "r", local: false },
  { name: "SQL", icon: "mysql", local: false },
  { name: "dbt", icon: "dbt", local: false },
  { name: "Grafana", icon: "grafana", local: false },
  { name: "Power BI", icon: "microsoft-power-bi.svg", local: true },
  { name: "Tableau", icon: "tableau-icon.svg", local: true },
  { name: "Metabase", icon: "metabase", local: false },
  { name: "Kafka", icon: "apachekafka", local: false },
  { name: "Airbyte", icon: "airbyte", local: false },
  { name: "AWS S3", icon: "aws-s3.svg", local: true },
  { name: "BigQuery", icon: "googlebigquery", local: false },
  { name: "Redshift", icon: "aws-redshift.svg", local: true },
  { name: "AWS RDS", icon: "aws-rds.svg", local: true },
  { name: "Lambda", icon: "aws-lambda.svg", local: true },
  { name: "Azure", icon: "microsoft-azure.svg", local: true },
  { name: "PostHog", icon: "posthog", local: false },
  { name: "Mixpanel", icon: "mixpanel", local: false },
];

export const techStackDev = [
  { name: "TypeScript", icon: "typescript", local: false },
  { name: "React", icon: "react", local: false },
  { name: "Next.js", icon: "nextdotjs", local: false },
  { name: "Node.js", icon: "nodedotjs", local: false },
  { name: "Git", icon: "git", local: false },
  { name: "HTML/CSS", icon: "html5", local: false },
  { name: "Tailwind", icon: "tailwindcss", local: false },
  { name: "Prisma", icon: "prisma", local: false },
  { name: "Docker", icon: "docker", local: false },
  { name: "AWS", icon: "aws.svg", local: true },
  { name: "JavaScript", icon: "javascript", local: false },
  { name: "Vercel", icon: "vercel", local: false },
  { name: "Firebase", icon: "firebase", local: false },
  { name: "Express.js", icon: "express", local: false },
  { name: "MongoDB", icon: "mongodb", local: false },
  { name: "Vite", icon: "vite", local: false },
  { name: "Jest", icon: "jest", local: false },
  { name: "GitHub", icon: "github", local: false },
  { name: "Postman", icon: "postman", local: false },
  { name: "Figma", icon: "figma", local: false },
  { name: "GitLab", icon: "gitlab", local: false },
  { name: "Cypress", icon: "cypress", local: false },
  { name: "AWS EC2", icon: "aws-ec2.svg", local: true },
  { name: "DigitalOcean", icon: "digitalocean", local: false },
  { name: "Mural", icon: "mural", local: false },
  { name: "Miro", icon: "miro", local: false },
];
